### ISSUE TITLE
Some fields are not translated

### ISSUE THREAD

**Issue by Kvarkas** [wpexplorer/wpex-blogger#7]
Hello, just make a PR with translation however something not right maybe you can check in code? 
![image](https://user-images.githubusercontent.com/3611964/169139849-6b7cf2eb-6c17-4232-b46b-31f850611bd3.png)

in admin mode under Appearance its still show as Theme Details even if have string in translation for same 
same issue on button bellow image
(submitted a PR to fix such)

tags not have translation strings in .mo file for threaded-comments, custom-menu and translation-ready - but unsure if it that theme dependency or WordPress it self.
Under Theme settings > Colors, Select Color dont have string for translation 
![image](https://user-images.githubusercontent.com/3611964/169140320-8b2364a4-2dec-4989-bdd9-dd9ee900ab94.png)

Thanks a lot for great work!

**Comment by wpexplorer** [comment]
Thanks for reporting the bugs!

The "Select Color" is a WordPress function because the color picker comes directly form the WP Customizer.

**Comment by wpexplorer** [comment]
@Kvarkas - I pushed out a 2.2 update with added optimizations if you want to take a look. Thank you again for providing Russian translation and fixes!!
